name: CI/CDd

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [14.21.3]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Change branch
      run: git checkout develop

    - name: Install dependencies
      run: npm install

    - name: Deploy
      run: |
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
