name: Github Page Deploy Pages

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.21.3"
      
      - run: git checkout develop
      
      - run: npm ci

      - run: npm run build
